/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern int writeBlockComment ( char *message, FILE *fp );

#else /* __STDC__ */

extern int writeBlockComment ( char *message, FILE *fp );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
