/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern void rinplace ( char *haystack, const char *needle, const char *sub );
extern void rinplace_huge ( char *haystack, const char *needle, const char *sub );

#else /* __STDC__ */

extern void rinplace ( char *haystack, const char *needle, const char *sub );
extern void rinplace_huge ( char *haystack, const char *needle, const char *sub );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
