/*
 *   This file was automatically generated by version 1.7 of cextract.
 *   Manual editing not recommended.
 */

#ifndef __CEXTRACT__
#ifdef __STDC__

extern void createModConObj ( char *name, struct dynArray *targetObjList, int index, short isPort, short direction, int slice[2] );
extern void createModConObjs ( struct dynArray *nameList, struct dynArray *targetObjList, int index, short isPort, short direction, int slice[2] );
extern void createModConObjsFromRange ( struct dynArray *nameList, struct dynArray *targetObjList, short isPort, short direction, int slice[2] );
extern void createSingleActual ( struct dynArray *targetList, char *name, int index );
extern void createMulActual ( struct dynArray *targetList, char *name, int start, int end );
extern struct portMapping *newPortMapping ( void );
extern void portMappingFree ( struct portMapping *ppntr );
extern void portMappingReset ( struct portMapping *ppntr );
extern void createPortMapping ( struct portMapping *ppntr, struct dynArray *formals, struct dynArray *actuals );
extern void createImplicitPortMapping ( struct portMapping *ppntr, struct dynArray *actuals );
extern void createInstantiation ( char *name, struct portMapping *pMap, struct dynArray *targetList );
extern int createSanitizedModule ( struct dynArray *targetList, struct dynArray *modConObjList, struct dynArray *modInstList, char *name );
extern int instanceSanitize ( struct instance *ipntr, struct dynArray *conObjList );
extern void dbgPrintSinglePortMapping ( struct portMapping *ppntr );

#else /* __STDC__ */

extern void createModConObj ( char *name, struct dynArray *targetObjList, int index, short isPort, short direction, int slice[2] );
extern void createModConObjs ( struct dynArray *nameList, struct dynArray *targetObjList, int index, short isPort, short direction, int slice[2] );
extern void createModConObjsFromRange ( struct dynArray *nameList, struct dynArray *targetObjList, short isPort, short direction, int slice[2] );
extern void createSingleActual ( struct dynArray *targetList, char *name, int index );
extern void createMulActual ( struct dynArray *targetList, char *name, int start, int end );
extern struct portMapping *newPortMapping ( void );
extern void portMappingFree ( struct portMapping *ppntr );
extern void portMappingReset ( struct portMapping *ppntr );
extern void createPortMapping ( struct portMapping *ppntr, struct dynArray *formals, struct dynArray *actuals );
extern void createImplicitPortMapping ( struct portMapping *ppntr, struct dynArray *actuals );
extern void createInstantiation ( char *name, struct portMapping *pMap, struct dynArray *targetList );
extern int createSanitizedModule ( struct dynArray *targetList, struct dynArray *modConObjList, struct dynArray *modInstList, char *name );
extern int instanceSanitize ( struct instance *ipntr, struct dynArray *conObjList );
extern void dbgPrintSinglePortMapping ( struct portMapping *ppntr );

#endif /* __STDC__ */
#endif /* __CEXTRACT__ */
